# Generated by Django 5.2.7 on 2025-11-02 07:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import ocr_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پرسنلی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('case_description', models.TextField(verbose_name='شرح پرونده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('MUST_CHANGE_PASSWORD', models.BooleanField(default=True, verbose_name='نیاز به تغییر رمز')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='دپارتمان')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پوشه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='ocr_app.folder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='ocr_app.person')),
            ],
            options={
                'verbose_name': 'پوشه',
                'verbose_name_plural': 'پوشه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=ocr_app.models.document_upload_path, verbose_name='فایل اصلی')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع فایل')),
                ('description', models.TextField(blank=True, verbose_name='شرح سند')),
                ('extracted_text', models.TextField(blank=True, verbose_name='متن استخراج شده')),
                ('extraction_confidence', models.FloatField(default=0, verbose_name='دقت استخراج')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='پردازش شده')),
                ('scan_queue_position', models.IntegerField(default=0, verbose_name='موقعیت در صف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ocr_app.folder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocr_app.person')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['scan_queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_app.document')),
            ],
            options={
                'verbose_name': 'صف اسکن',
                'verbose_name_plural': 'صف اسکن',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('person_management', 'مدیریت افراد'), ('document_upload', 'آپلود اسناد'), ('document_view', 'مشاهده اسناد'), ('search', 'جستجو'), ('ocr_processing', 'پردازش OCR'), ('user_management', 'مدیریت کاربران'), ('system_admin', 'مدیریت سیستم')], max_length=50)),
                ('granted', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسترسی کاربر',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
