# Generated by Django 5.2.7 on 2025-10-26 16:43

import django.db.models.deletion
import ocr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('case_description', models.TextField(verbose_name='شرح پرونده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پوشه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='ocr_app.folder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='ocr_app.person')),
            ],
            options={
                'verbose_name': 'پوشه',
                'verbose_name_plural': 'پوشه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=ocr_app.models.document_upload_path, verbose_name='فایل اصلی')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع فایل')),
                ('description', models.TextField(blank=True, verbose_name='شرح سند')),
                ('extracted_text', models.TextField(blank=True, verbose_name='متن استخراج شده')),
                ('extraction_confidence', models.FloatField(default=0, verbose_name='دقت استخراج')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='پردازش شده')),
                ('scan_queue_position', models.IntegerField(default=0, verbose_name='موقعیت در صف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ocr_app.folder')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocr_app.person')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['scan_queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_app.document')),
            ],
            options={
                'verbose_name': 'صف اسکن',
                'verbose_name_plural': 'صف اسکن',
            },
        ),
    ]
